# 1.1.Arrays

# Exercise 1.1

In [11]:
import numpy as NP
aa=NP.array([[3,-1,4],[1,5,-9]])
bb=NP.array([[2,4,-5,6],[-1,7,9,3],[3,2,-7,-2]])
print(NP.dot(aa,bb))


[[ 19  13 -52   7]
 [-30  21 103  39]]


# Exercise 1.2

In [5]:
a = NP.array([3, 4, 2, 1])
a.partition(3)
a

array([2, 1, 3, 4])

# 1.2.Basic Array Operations

# Exercise 1.3

In [6]:
import numpy as NP
aa=NP.array([3,-4,1])
bb=NP.array([5,2,3])
print(aa+10)
print(bb*4)
print(aa+bb)
print(aa*bb)

[13  6 11]
[20  8 12]
[ 8 -2  4]
[15 -8  3]


# 1.4.Array Attributes

# Exercise 1.4

In [7]:
import numpy as NP
aa=NP.array([[1,2,3],[4,5,6]])
print(aa.ndim)
print(aa.shape)
print(aa.size)

2
(2, 3)
6


# Exercise 1.5

In [9]:
import numpy as NP
aa=NP.array([[1,2,3],[4,5,6]])
print(aa.dtype)
aa=aa.astype('float64')
print(aa.dtype)

int32
float64


# 1.5.Data Access

## 1.5.1Array Slicing

### What does x = np.arange(10) do? 

In [18]:
import numpy as NP
x=NP.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


# Exercise 1.6

In [21]:
import numpy as NP
x=NP.arange(10)
print(x[3])
print(x[: 4])
print(x[4 :])
print(x[4:8])

3
[0 1 2 3]
[4 5 6 7 8 9]
[4 5 6 7]


# Exercise 1.7

In [22]:
import numpy as NP
x=NP.array([[0,1,2,3,4],[5,6,7,8,9]])
print(x[1,2]) ##row 1 col from 0 to 2
print(x[:,2:])

7
[[2 3 4]
 [7 8 9]]


# 2.Working on Iris.csv file

In [23]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.filename)

C:\Users\RaKaN\Anaconda3\lib\site-packages\sklearn\datasets\data\iris.csv


In [26]:
import numpy as NP
iris_data = NP.genfromtxt('C:\\Users\\RaKaN\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\iris.csv',
                          delimiter=",", skip_header=1)
print(iris_data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

# Exercise 2

In [25]:
print("mean of {} is {}" .format(iris.feature_names[0],iris_data[:,0].mean()))
print("Variance of {} is {}" .format(iris.feature_names[0],iris_data[:,0].var()))
print("Max of {} is {}" .format(iris.feature_names[0],iris_data[:,0].max()))
print("Min of {} is {}" .format(iris.feature_names[0],iris_data[:,0].min()))
print("Stander dvision of {} is {}" .format(iris.feature_names[0],iris_data[:,0].std()))

mean of sepal length (cm) is 5.843333333333334
Variance of sepal length (cm) is 0.6811222222222223
Max of sepal length (cm) is 7.9
Min of sepal length (cm) is 4.3
Stander dvision of sepal length (cm) is 0.8253012917851409
